packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@prisma/engines': true
  esbuild: set this to true or false
  msgpackr-extract: set this to true or false
  prisma: true
  workerd: set this to true or false
